apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win2022
  labels:
    # insert any desired labels to identify your claim
    app: win2022
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # The amount of the volume's storage to request
      storage: 64Gi
